spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: baseball
    version: 1.2.1



  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    root: info
    com.game.baseball: debug
server:
  servlet:
    session:
      context-path: baseball
      timeout: 1m

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.game.baseball.model

file:
  path: /home/baseball/src/main/resources/py/json/todaysGames

py:
  paths:
    mlb:
      schedule: /home/baseball/src/main/resources/py/getTodayMLBgame.py
      result: /home/baseball/src/main/resources/py/getCurMLBrslt.py
    kbo:
      schedule: /home/baseball/src/main/resources/py/getTodayKBOgame.py
      result: /home/baseball/src/main/resources/py/getCurKBOrslt.py
    gpt:
      exepect: /home/baseball/src/main/resources/py/getBaseBallRating.py

schedule:
  cron: "0 0 * * * ?"