spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: baseball
    version: 1.0.0

  datasource:
    url: jdbc:mysql://192.168.0.78:3306/testDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: studyuser
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    root: info
    com.game.baseball: debug
server:
  servlet:
    session:
      timeout: 1m

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.game.baseball.model
